name = "backend"
compatibility_date = "2023-12-01"
main = "./src/index.ts"
    

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDllODk4ODgtNTA2ZS00YzUxLWE2OGQtYzU3MWRhNWQ5MTFiIiwidGVuYW50X2lkIjoiNzY1NzY3ODRiNmJlZTNhMzkzY2VhODA1NzRhY2Q2MTAzZjA5Njk5NzY1OWFlYzBiMWJhYWRiZjg0M2YzN2MyYSIsImludGVybmFsX3NlY3JldCI6ImM2MzMyNmVmLTFkNjYtNDBjZC1iNzIyLTlhMjA3NGFjMGFmNSJ9.lc1Iol4TDecq_ppKA1KxYFK8tY9tSLJ8QtTkVQILboE"

JWT_SECRET="asdfasd"